/* eslint-disable */
/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import { a } from "@aws-amplify/data-schema";
import { configure } from "@aws-amplify/data-schema/internals";
import { secret } from "@aws-amplify/backend";

export const schema = configure({
    database: {
        identifier: "IDDbpbGQellLnedEB4uZXWbA",
        engine: "postgresql",
        connectionUri: secret("DBConnectionURI"),
        vpcConfig: {
            vpcId: "vpc-0aca5b3449508fb77",
            securityGroupIds: [
                "sg-0cb2de8762992aeee"
            ],
            subnetAvailabilityZones: [
                {
                    subnetId: "subnet-0e87cf5a61dfebffd",
                    availabilityZone: "us-east-1a"
                },
                {
                    subnetId: "subnet-07cac16f02d40327b",
                    availabilityZone: "us-east-1d"
                },
                {
                    subnetId: "subnet-0536733b16815f719",
                    availabilityZone: "us-east-1b"
                },
                {
                    subnetId: "subnet-06e440c3ac92bec14",
                    availabilityZone: "us-east-1e"
                },
                {
                    subnetId: "subnet-020d6055ca418faa4",
                    availabilityZone: "us-east-1f"
                },
                {
                    subnetId: "subnet-0a7717d7848666097",
                    availabilityZone: "us-east-1c"
                }
            ]
        }
    }
}).schema({
    "comments": a.model({
        id: a.integer().default(),
        post_id: a.integer().required(),
        user_id: a.integer().required(),
        content: a.string().required(),
        created_at: a.datetime()
    }).identifier([
        "id"
    ]),
    "posts": a.model({
        id: a.integer().default(),
        user_id: a.integer().required(),
        title: a.string().required(),
        content: a.string().required(),
        created_at: a.datetime()
    }).identifier([
        "id"
    ]),
    "users": a.model({
        id: a.integer().default(),
        name: a.string().required(),
        email: a.string().required(),
        created_at: a.datetime()
    }).identifier([
        "id"
    ])
});
